# Generated by Django 6.0.6 on 2026-07-02 18:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FATURA', 'Fatura'), ('COTACAO', 'Cotação')], default='FATURA', max_length=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDO', 'Emitido'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=10)),
                ('taxa_imposto', models.DecimalField(decimal_places=4, default=Decimal('0.16'), help_text='Fração aplicada sobre o subtotal (ex.: 0.16 = 16%).', max_digits=5, verbose_name='Alíquota de imposto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='loja.cliente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.documento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_documento', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Item do documento',
                'verbose_name_plural': 'Itens do documento',
                'unique_together': {('documento', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='produtos',
            field=models.ManyToManyField(related_name='documentos', through='core.ItemDocumento', to='loja.produto'),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('COMPRA', 'Compra de fornecedor'), ('VENDA', 'Venda'), ('AJUSTE', 'Ajuste manual'), ('DEVOLUCAO', 'Devolução')], default='AJUSTE', max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='core.documento')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='loja.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-data'],
            },
        ),
    ]
