"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lê o arquivo .env e guarda os dados em uma variável chamada 'config'
# config = dotenv_values(Path(__file__).resolve().parent.parent / ".env")
ENV_PATH = BASE_DIR / ".env"

# 2. Tenta ler o arquivo diretamente
config = dotenv_values(ENV_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config.get("SECRET_KEY", "django-insecure-fallback-key-change-this-in-production")

# Converte o valor do .env para Booleano de forma segura (Padrão: False se omitido)
DEBUG = config.get("DEBUG", "True").lower() in ("true", "1", "t")

ALLOWED_HOSTS = config.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    # 1. MÓDULOS DO ADMINLTE 4 E COMPONENTES (Ajustado com o módulo seguro)
    'django_components',
    'adminlte4',
    'adminlte4_theme',

    # 2. APPS NATIVOS DO DJANGO
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3. OUTROS COMPONENTES
    'localflavor',
    'phonenumber_field',

    # 4. APPS LOCAIS
    'loja.apps.LojaConfig',  # Mudado de 'loja' para este caminho completo
    'core.apps.CoreConfig',  # Mudado de 'core' para este caminho completo
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config.get("DB_NAME"),
        "USER": config.get("DB_USER"),
        "PASSWORD": config.get("DB_PASSWORD"),
        "HOST": config.get("DB_HOST"),
        "PORT": config.get("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 1. URL usada no navegador para acessar os arquivos
STATIC_URL = 'static/'

# 2. Caminho onde o Django vai JUNTAR todos os arquivos ao rodar o collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 3. Pastas adicionais onde você pode colocar seus próprios arquivos de CSS/JS locais
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Buscadores de arquivos estáticos necessários para o ecossistema funcionar
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

PHONENUMBER_DEFAULT_REGION = 'BR'

# Controle de acessos e rotas do login
# LOGIN_URL = '/accounts/login/'
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'admin:index'
LOGOUT_REDIRECT_URL = 'admin:login'
